from models import Plant

plantseed = [
    Plant(
        common_name="Java Moss",
        scientific_name="Taxiphyllum barbieri",
        bio="Java Moss (Taxiphyllum barbieri) is a versatile and popular aquatic plant prized by aquarium enthusiasts for its hardiness and ease of care. Originating from Southeast Asia, this plant is commonly found attached to rocks, driftwood, or other surfaces in its natural habitat. In the aquarium, Java Moss adds a lush, green carpeting effect and provides hiding places for fry and small fish. Its fine, branching structure creates a natural and aesthetic look, making it a favorite choice for aquascaping. Java Moss thrives in low to moderate lighting conditions and can tolerate a wide range of water parameters. It propagates readily and can be easily attached to decor or left to float freely. Its ability to absorb nutrients makes it beneficial for maintaining water quality and promoting a healthy aquatic environment.",
        origin="Southeast Asia",
        care_level="Easy",
        lighting_needs="Low to moderate",
        substrate="Doesn't require substrate, but can be attached to decor",
        image="./static/java_moss.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Anubias Nana Petite",
        scientific_name="Anubias barteri var. nana 'Petite'",
        bio="Anubias Nana Petite is a compact and charming variety of Anubias prized by aquarium enthusiasts for its small size and attractive appearance. Originating from West Africa, it is a dwarf form of the larger Anubias barteri species. Anubias Nana Petite features dark green, heart-shaped leaves that grow on short stems, making it suitable for small aquariums or as a foreground plant in larger setups. It is known for its low maintenance requirements and ability to thrive in various water conditions. Anubias Nana Petite prefers low to moderate lighting and can be attached to rocks, driftwood, or other decor using thread or glue. Its slow growth rate and compact size make it an ideal choice for aquascaping. This plant adds a touch of elegance to any freshwater aquarium.",
        origin="West Africa",
        care_level="Easy",
        lighting_needs="Low to moderate",
        substrate="Can be attached to decor or planted in substrate",
        image="./static/anubias_nana_petite.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Java Fern",
        scientific_name="Microsorum pteropus",
        bio="Java Fern (Microsorum pteropus) is a popular and versatile aquatic plant known for its distinctive and attractive appearance. Native to Southeast Asia, it is commonly found attached to rocks or driftwood in streams and rivers. In the aquarium, Java Fern adds a lush green color and a unique texture to the aquascape. Its tough, leathery leaves are resistant to most herbivorous fish and invertebrates, making it an ideal choice for community tanks. Java Fern thrives in low to moderate lighting conditions and can tolerate a wide range of water parameters. It propagates by producing daughter plants on its leaves, which can be separated and attached to decor or left to grow independently. Java Fern is a great addition to any freshwater aquarium, providing beauty and habitat for fish and other aquatic",
        origin="Southeast Asia",
        care_level="Easy",
        lighting_needs="Low to moderate",
        substrate="Doesn't require substrate, but can be attached to decor",
        image="./static/java_fern.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Amazon Sword",
        scientific_name="Echinodorus amazonicus",
        bio="Amazon Sword (Echinodorus amazonicus) is a popular choice for freshwater aquariums due to its striking appearance and relatively easy care. Originating from South America, it is found in the Amazon River basin and other waterways. In the aquarium, Amazon Sword adds a dramatic and vibrant focal point with its long, sword-shaped leaves. It is a popular choice for background planting due to its large size and ability to fill out the back of the tank. Amazon Sword prefers moderate to high lighting and nutrient-rich substrate. It is a heavy feeder and benefits from regular fertilization. This plant can grow quite large, so it's important to provide adequate space in the aquarium. Amazon Sword provides shelter for fish and other aquatic creatures, making it a valuable addition to any freshwater setup.",
        origin="South America",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/amazon_sword.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Wendtii",
        scientific_name="Cryptocoryne wendtii",
        bio="Cryptocoryne Wendtii (Cryptocoryne wendtii) is a popular and versatile aquatic plant known for its hardiness and attractive appearance. Native to Sri Lanka, India, and other parts of Southeast Asia, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Wendtii adds a touch of elegance with its broad, green leaves and low-growing habit. It is an excellent choice for midground or background planting, where it can form dense clusters and provide shelter for fish and other aquatic creatures. Cryptocoryne Wendtii is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and nutrient-rich substrate. Propagation is achieved through rhizome division or by separating daughter plants. Cryptocoryne Wendtii is a popular choice for aquascaping due to its versatility and ability to thrive in various setups.",
        origin="Sri Lanka, India, Southeast Asia",
        care_level="Easy",
        lighting_needs="Low to moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_wendtii.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Water Wisteria",
        scientific_name="Hygrophila difformis",
        bio="Water Wisteria (Hygrophila difformis) is a fast-growing and easy-to-care-for aquatic plant native to the Indian subcontinent. Also known as Indian Waterweed, it is commonly found in marshes, swamps, and slow-moving streams. In the aquarium, Water Wisteria is valued for its attractive appearance and ability to quickly fill out the background or midground of the tank. It features delicate, fern-like leaves that add a touch of elegance to any aquascape. Water Wisteria is an excellent choice for beginners due to its low maintenance requirements and ability to thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from regular fertilization. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Water Wisteria is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Indian subcontinent",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/water_wisteria.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Dwarf Sagittaria",
        scientific_name="Sagittaria subulata",
        bio="Dwarf Sagittaria (Sagittaria subulata) is a popular choice for freshwater aquariums due to its graceful appearance and ease of care. Native to North and South America, it is commonly found in shallow waters, marshes, and along the edges of ponds and streams. In the aquarium, Dwarf Sagittaria forms dense clusters of narrow, grass-like leaves that add a natural and aesthetic look to the aquascape. It is an excellent choice for foreground planting, where it can create a carpeting effect and provide habitat for small fish and invertebrates. Dwarf Sagittaria is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved through runners, which can be replanted to create new clusters. Dwarf Sagittaria is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="North and South America",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/dwarf_sagittaria.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Hornwort",
        scientific_name="Ceratophyllum demersum",
        bio="Hornwort (Ceratophyllum demersum) is a fast-growing and versatile aquatic plant prized by aquarium enthusiasts for its hardiness and ease of care. Native to North America, Europe, and parts of Asia, it is commonly found in ponds, lakes, and slow-moving streams. In the aquarium, Hornwort forms dense, bushy clusters of fine, needle-like leaves that provide shelter for fish and other aquatic creatures. Its rapid growth rate makes it an excellent choice for controlling algae and improving water quality. Hornwort is an ideal choice for beginners due to its low maintenance requirements and ability to thrive in a wide range of water parameters. It prefers moderate to high lighting and can be left to float or anchored to decor using weights. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Hornwort is a valuable addition to any freshwater setup, providing beauty, habitat, and natural filtration.",
        origin="North America, Europe, Asia",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Doesn't require substrate, can be left to float or anchored",
        image="./static/hornwort.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Italian Vallisneria",
        scientific_name="Vallisneria spiralis",
        bio="Italian Vallisneria (Vallisneria spiralis) is a popular and attractive aquatic plant known for its long, ribbon-like leaves and ease of care. Native to Europe, Asia, and Africa, it is commonly found in freshwater rivers, streams, and lakes. In the aquarium, Italian Vallisneria forms dense clusters of tall, grass-like leaves that create a striking vertical accent in the aquascape. It is an excellent choice for background planting, where it can provide shelter for fish and other aquatic creatures. Italian Vallisneria is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by runners, which can be replanted to create new clusters. Italian Vallisneria is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Europe, Asia, Africa",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/vall_spiralis.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Dwarf Hairgrass",
        scientific_name="Eleocharis acicularis",
        bio="Dwarf Hairgrass (Eleocharis acicularis) is a popular and versatile aquatic plant known for its fine, grass-like leaves and low-growing habit. Native to North America, it is commonly found in shallow waters, marshes, and along the edges of ponds and streams. In the aquarium, Dwarf Hairgrass forms dense carpets of greenery that add a natural and aesthetic look to the aquascape. It is an excellent choice for foreground planting, where it can create a lush carpet and provide habitat for small fish and invertebrates. Dwarf Hairgrass is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by runners, which can be replanted to create new clusters. Dwarf Hairgrass is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="North America",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/dwarf_hairgrass.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Ludwigia Repens",
        scientific_name="Ludwigia repens",
        bio="Ludwigia Repens (Ludwigia repens) is a vibrant and popular aquatic plant prized by aquarium enthusiasts for its striking coloration and ease of care. Native to North and Central America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Ludwigia Repens adds a splash of red or orange color to the aquascape with its narrow, pointed leaves. It is an excellent choice for background or midground planting, where it can create a striking contrast against greenery or serve as a focal point. Ludwigia Repens is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from regular fertilization. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Ludwigia Repens is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="North and Central America",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/ludwigia_repens.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Rotala Rotundifolia",
        scientific_name="Rotala rotundifolia",
        bio="Rotala Rotundifolia (Rotala rotundifolia) is a popular and attractive aquatic plant known for its delicate appearance and vibrant coloration. Native to Southeast Asia, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Rotala Rotundifolia forms dense clusters of thin, branching stems that create a bushy and graceful effect in the aquascape. Its narrow, pointed leaves range in color from green to red, depending on the lighting conditions and nutrient levels. Rotala Rotundifolia is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from regular fertilization. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Rotala Rotundifolia is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Southeast Asia",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/rotala-rotundifolia.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Water Sprite",
        scientific_name="Ceratopteris thalictroides",
        bio="Water Sprite (Ceratopteris thalictroides) is a popular and versatile aquatic plant known for its delicate appearance and ease of care. Native to tropical regions around the world, it is commonly found in ponds, lakes, and slow-moving streams. In the aquarium, Water Sprite adds a touch of elegance with its fine, lacy leaves and graceful growth habit. It is an excellent choice for midground or background planting, where it can provide shelter for fish and other aquatic creatures. Water Sprite is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from regular fertilization. Propagation is achieved by division, as new plantlets develop at the ends of its leaves. Water Sprite is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Tropical regions worldwide",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Doesn't require substrate, but can be planted in substrate",
        image="./static/water_sprite.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Amazon Frogbit",
        scientific_name="Limnobium laevigatum",
        bio="Amazon Frogbit (Limnobium laevigatum) is a popular floating plant prized by aquarium enthusiasts for its attractive appearance and ease of care. Native to South America, it is commonly found in ponds, lakes, and slow-moving rivers. In the aquarium, Amazon Frogbit forms dense mats of round, glossy leaves that float on the surface of the water. Its long, trailing roots provide shelter for fish and other aquatic creatures while absorbing excess nutrients from the water. Amazon Frogbit is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from regular fertilization. Propagation is achieved by division, as new plants develop from daughter plants at the base of the parent plant. Amazon Frogbit is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="South America",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Floating plant",
        image="./static/amazon_frogbit.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Parva",
        scientific_name="Cryptocoryne parva",
        bio="Cryptocoryne Parva (Cryptocoryne parva) is a charming and compact aquatic plant prized by aquarium enthusiasts for its small size and attractive appearance. Native to Sri Lanka, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Parva forms dense clusters of narrow, lance-shaped leaves that create a lush carpeting effect in the foreground. It is an excellent choice for nano tanks or small aquariums, where it can provide habitat for small fish and invertebrates. Cryptocoryne Parva is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Parva is a versatile and adaptable plant that can be used in various setups, from planted aquariums to paludariums.",
        origin="Sri Lanka",
        care_level="Moderate",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_parva.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Balansae",
        scientific_name="Cryptocoryne balansae",
        bio="Cryptocoryne Balansae (Cryptocoryne balansae) is a beautiful and graceful aquatic plant prized by aquarium enthusiasts for its tall and slender appearance. Native to Southeast Asia, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Balansae forms dense clusters of long, lance-shaped leaves that create a striking vertical accent in the aquascape. It is an excellent choice for background planting, where it can provide shelter for fish and other aquatic creatures. Cryptocoryne Balansae is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Balansae is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Southeast Asia",
        care_level="Moderate",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_balansae.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Duckweed",
        scientific_name="Lemna minor",
        bio="Duckweed (Lemna minor) is a small and fast-growing floating plant prized by aquarium enthusiasts for its ability to provide shade and cover for fish while absorbing excess nutrients from the water. Native to temperate and tropical regions worldwide, it is commonly found in ponds, lakes, and slow-moving streams. In the aquarium, Duckweed forms dense mats of tiny, rounded leaves that float on the surface of the water. Its rapid growth rate makes it an excellent choice for controlling algae and improving water quality. Duckweed is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from regular fertilization. Propagation is achieved by division, as new plants develop from daughter plants that grow at the base of the parent plant. Duckweed is a versatile and adaptable plant that can be used in various setups, from community tanks to outdoor ponds.",
        origin="Worldwide",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Floating plant",
        image="./static/duckweed.jpg",
        filtration=1
    ),
    Plant(
        common_name="Monte Carlo",
        scientific_name="Micranthemum tweediei",
        bio="Monte Carlo (Micranthemum tweediei) is a popular and attractive aquatic plant known for its vibrant green color and low-growing habit. Native to South America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Monte Carlo forms dense carpets of small, round leaves that create a lush and carpet-like effect in the foreground. It is an excellent choice for nano tanks or small aquariums, where it can provide habitat for small fish and invertebrates. Monte Carlo is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Monte Carlo is a versatile and adaptable plant that can be used in various setups, from planted aquariums to paludariums.",
        origin="South America",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/monte_carlo.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Christmas Moss",
        scientific_name="Vesicularia montagnei",
        bio="Christmas Moss (Vesicularia montagnei) is a popular and attractive aquatic plant prized by aquarium enthusiasts for its delicate appearance and versatility. Native to Southeast Asia, it is commonly found in streams, rivers, and marshes. In the aquarium, Christmas Moss forms dense mats of fine, feathery leaves that create a lush and natural look in the aquascape. It is an excellent choice for creating moss walls, attaching to driftwood or rocks, or carpeting the substrate. Christmas Moss is relatively easy to care for and can thrive in a wide range of water parameters. It prefers low to moderate lighting and benefits from occasional trimming to maintain its shape and density. Propagation is achieved by division or by separating small portions of the moss and attaching them to decor. Christmas Moss is a versatile and adaptable plant that can be used in various setups, from nano tanks to large planted aquariums.",
        origin="Southeast Asia",
        care_level="Easy",
        lighting_needs="Low to moderate",
        substrate="Can be attached to decor or carpeted",
        image="./static/christmas_moss.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Staurogyne Repens",
        scientific_name="Staurogyne repens",
        bio="Staurogyne Repens (Staurogyne repens) is a popular and versatile aquatic plant known for its compact growth habit and attractive appearance. Native to South America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Staurogyne Repens forms dense clusters of small, bright green leaves that create a lush and carpet-like effect in the foreground. It is an excellent choice for nano tanks or small aquariums, where it can provide habitat for small fish and invertebrates. Staurogyne Repens is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Staurogyne Repens is a versatile and adaptable plant that can be used in various setups, from planted aquariums to terrariums.",
        origin="South America",
        care_level="Moderate",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/staurogyne_repens.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Flame Moss",
        scientific_name="Taxiphyllum 'Flame'",
        bio="Flame Moss (Taxiphyllum 'Flame') is a unique and eye-catching aquatic moss prized by aquarium enthusiasts for its vibrant red coloration and distinctive appearance. Originating from Southeast Asia, it is commonly found in streams, rivers, and marshes. In the aquarium, Flame Moss forms dense mats of fine, branching filaments that resemble flickering flames, hence its name. It is an excellent choice for attaching to driftwood, rocks, or other decor to create striking focal points in the aquascape. Flame Moss is relatively easy to care for and can thrive in a wide range of water parameters. It prefers low to moderate lighting and benefits from occasional trimming to maintain its shape and color. Propagation is achieved by division or by separating small portions of the moss and attaching them to decor. Flame Moss is a versatile and adaptable plant that can be used in various setups, from nano tanks to large planted aquariums.",
        origin="Southeast Asia",
        care_level="Moderate",
        lighting_needs="Low to moderate",
        substrate="Can be attached to decor",
        image="./static/flame_moss.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Dwarf Baby Tears",
        scientific_name="Hemianthus callitrichoides",
        bio="Dwarf Baby Tears (Hemianthus callitrichoides) is a popular and challenging aquatic plant known for its lush carpeting effect and delicate appearance. Originating from North America, it is commonly found in shallow waters, marshes, and along the edges of ponds and streams. In the aquarium, Dwarf Baby Tears forms dense carpets of tiny, bright green leaves that create a striking and carpet-like effect in the foreground. It is an excellent choice for creating intricate aquascapes and providing habitat for small fish and invertebrates. Dwarf Baby Tears requires high lighting and nutrient-rich substrate to thrive. It is a demanding plant that requires consistent care and maintenance, including CO2 supplementation and regular trimming. Propagation is achieved by dividing the plant into small portions and planting them close together to encourage new growth. Dwarf Baby Tears is a challenging but rewarding plant that can create stunning visual effects in the aquarium.",
        origin="North America",
        care_level="Difficult",
        lighting_needs="High",
        substrate="Nutrient-rich substrate",
        image="./static/dwarf_baby_tears.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Alternanthera Reineckii",
        scientific_name="Alternanthera reineckii",
        bio="Alternanthera Reineckii (Alternanthera reineckii) is a vibrant and attractive aquatic plant known for its striking coloration and distinctive appearance. Native to South America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Alternanthera Reineckii forms dense clusters of bright red or pink leaves that create a bold and eye-catching focal point in the aquascape. It is an excellent choice for midground or background planting, where it can provide contrast against greenery or serve as a colorful accent. Alternanthera Reineckii is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Alternanthera Reineckii is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="South America",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/alter_reineckii.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Lutea",
        scientific_name="Cryptocoryne lutea",
        bio="Cryptocoryne Lutea (Cryptocoryne lutea) is a popular and versatile aquatic plant known for its hardiness and attractive appearance. Native to Sri Lanka and parts of India, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Lutea forms dense clusters of broad, lance-shaped leaves that create a lush and natural look in the aquascape. It is an excellent choice for midground or background planting, where it can provide shelter for fish and other aquatic creatures. Cryptocoryne Lutea is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Lutea is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Sri Lanka, India",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_lutea.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Undulata",
        scientific_name="Cryptocoryne undulata",
        bio="Cryptocoryne Undulata (Cryptocoryne undulata) is a popular and attractive aquatic plant known for its wavy leaves and ease of care. Native to Sri Lanka and parts of India, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Undulata forms dense clusters of broad, wavy leaves that create a lush and natural look in the aquascape. It is an excellent choice for midground or background planting, where it can provide shelter for fish and other aquatic creatures. Cryptocoryne Undulata is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Undulata is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Sri Lanka, India",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_undulata.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Lucens",
        scientific_name="Cryptocoryne lucens",
        bio="Cryptocoryne Lucens (Cryptocoryne lucens) is a popular and versatile aquatic plant known for its hardiness and attractive appearance. Native to Sri Lanka and parts of India, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Lucens forms dense clusters of narrow, lance-shaped leaves that create a lush and natural look in the aquascape. It is an excellent choice for midground or background planting, where it can provide shelter for fish and other aquatic creatures. Cryptocoryne Lucens is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Lucens is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Sri Lanka, India",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_lucens.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Giant Hygro",
        scientific_name="Hygrophila corymbosa",
        bio="Giant Hygro (Hygrophila corymbosa) is a popular and fast-growing aquatic plant known for its large, broad leaves and attractive appearance. Native to Southeast Asia, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Giant Hygro forms dense clusters of vibrant green leaves that create a lush and bushy effect in the aquascape. It is an excellent choice for background planting, where it can provide shelter for fish and other aquatic creatures. Giant Hygro is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Giant Hygro is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Southeast Asia",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/giant_hygro.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Red Tiger Lotus",
        scientific_name="Nymphaea lotus 'Red'",
        bio="Red Tiger Lotus (Nymphaea lotus 'Red') is a striking and vibrant aquatic plant prized by aquarium enthusiasts for its bold coloration and unique appearance. Native to Africa and parts of Asia, it is commonly found in shallow waters, marshes, and ponds. In the aquarium, Red Tiger Lotus forms rosettes of dark red or burgundy leaves that create a dramatic focal point in the aquascape. It is an excellent choice for midground or background planting, where it can provide contrast against greenery or serve as a centerpiece. Red Tiger Lotus is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by separating rhizomes or by planting new offshoots. Red Tiger Lotus is a versatile and adaptable plant that can add a splash of color to various setups, from community tanks to planted aquariums.",
        origin="Africa, Asia",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/red_tiger_lotus.jpg",
        filtration=1
    ),
    Plant(
        common_name="Brazilian Pennywort",
        scientific_name="Hydrocotyle leucocephala",
        bio="Brazilian Pennywort (Hydrocotyle leucocephala) is a popular and versatile aquatic plant known for its rapid growth and trailing habit. Native to Central and South America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Brazilian Pennywort forms dense mats of bright green leaves that create a lush and natural look in the aquascape. It is an excellent choice for background planting, where it can provide shelter for fish and other aquatic creatures. Brazilian Pennywort is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by stem cuttings, which can be replanted to create new clusters. Brazilian Pennywort is a fast-growing plant that can quickly fill in empty spaces in the aquarium.",
        origin="Central and South America",
        care_level="Easy",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/brazilian_pennywort.jpeg",
        filtration=1
    ),  
    Plant(
        common_name="Dwarf Lily",
        scientific_name="Nymphaea stellata",
        bio="Dwarf Lily (Nymphaea stellata) is a charming and compact aquatic plant prized by aquarium enthusiasts for its small size and attractive appearance. Native to India and parts of Southeast Asia, it is commonly found in shallow waters, marshes, and ponds. In the aquarium, Dwarf Lily forms rosettes of narrow, pointed leaves that create a striking visual impact in the aquascape. It is an excellent choice for midground or background planting, where it can provide contrast against greenery or serve as a focal point. Dwarf Lily is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate to high lighting and benefits from nutrient-rich substrate. Propagation is achieved by separating rhizomes or by planting new offshoots. Dwarf Lily is a versatile and adaptable plant that can add a touch of elegance to various setups, from community tanks to planted aquariums.",
        origin="India, Southeast Asia",
        care_level="Moderate",
        lighting_needs="Moderate to high",
        substrate="Nutrient-rich substrate",
        image="./static/dwarf_lilly.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Cryptocoryne Spiralis",
        scientific_name="Cryptocoryne spiralis",
        bio="Cryptocoryne Spiralis (Cryptocoryne spiralis) is a popular and versatile aquatic plant known for its graceful appearance and ease of care. Native to Sri Lanka and parts of India, it is commonly found in streams, rivers, and marshes. In the aquarium, Cryptocoryne Spiralis forms dense clusters of long, spiraling leaves that create a lush and natural look in the aquascape. It is an excellent choice for midground or background planting, where it can provide shelter for fish and other aquatic creatures. Cryptocoryne Spiralis is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by division, as new plants develop from runners that spread horizontally along the substrate. Cryptocoryne Spiralis is a versatile and adaptable plant that can be used in various setups, from community tanks to planted aquariums.",
        origin="Sri Lanka, India",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/crypt_spiralis.jpeg",
        filtration=1
    ),
    Plant(
        common_name="Amazon Compacta Sword",
        scientific_name="Echinodorus grisebachii 'Bleherae Compacta'",
        bio="Amazon Compacta Sword (Echinodorus grisebachii 'Bleherae Compacta') is a compact and attractive aquatic plant prized by aquarium enthusiasts for its bold foliage and ease of care. Originating from South America, it is commonly found in freshwater rivers, streams, and marshes. In the aquarium, Amazon Compacta Sword forms rosettes of broad, lance-shaped leaves that create a striking focal point in the aquascape. It is an excellent choice for midground or background planting, where it can provide contrast against greenery or serve as a centerpiece. Amazon Compacta Sword is relatively easy to care for and can thrive in a wide range of water parameters. It prefers moderate lighting and benefits from nutrient-rich substrate. Propagation is achieved by separating daughter plants or by planting new offshoots. Amazon Compacta Sword is a versatile and adaptable plant that can add a touch of elegance to various setups, from community tanks to planted aquariums.",
        origin="South America",
        care_level="Easy",
        lighting_needs="Moderate",
        substrate="Nutrient-rich substrate",
        image="./static/amazon_compacta.jpeg",
        filtration=1
    ),
]

