"""added other tables

Revision ID: 38eb9fcdabe7
Revises: 336b73371513
Create Date: 2024-03-13 10:15:07.724131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38eb9fcdabe7'
down_revision = '336b73371513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('maximum_bioload', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tanks'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('ownedfishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['freshwaterfishes.id'], name=op.f('fk_ownedfishes_fish_id_freshwaterfishes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ownedfishes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownedfishes'))
    )
    op.create_table('ownedplants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_ownedplants_plant_id_plants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ownedplants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownedplants'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownedplants')
    op.drop_table('ownedfishes')
    op.drop_table('users')
    op.drop_table('tanks')
    # ### end Alembic commands ###
