"""empty message

Revision ID: 6de371e80242
Revises: 
Create Date: 2024-03-12 16:37:06.704947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de371e80242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('care_level', sa.String(), nullable=True),
    sa.Column('lighting_needs', sa.String(), nullable=True),
    sa.Column('substrate', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('filtration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
